// Code generated by protoc-gen-go.
// source: protocol.proto
// DO NOT EDIT!

/*
Package index is a generated protocol buffer package.

It is generated from these files:
	protocol.proto

It has these top-level messages:
	Item
*/
package index

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Item struct {
	Fields []string `protobuf:"bytes,1,rep,name=fields" json:"fields,omitempty"`
	Value  uint32   `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
