// Code generated by protoc-gen-go.
// source: protocol.proto
// DO NOT EDIT!

/*
Package kadiyadb is a generated protocol buffer package.

It is generated from these files:
	protocol.proto

It has these top-level messages:
	Metadata
*/
package kadiyadb

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Metadata struct {
	// path to store files
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	// point resolution in nano seconds
	Resolution int64 `protobuf:"varint,2,opt,name=resolution" json:"resolution,omitempty"`
	// retention time in nano seconds
	Retention int64 `protobuf:"varint,3,opt,name=retention" json:"retention,omitempty"`
	// epoch duration in nano seconds
	Duration int64 `protobuf:"varint,4,opt,name=duration" json:"duration,omitempty"`
	// payload size in bytes
	PayloadSize uint32 `protobuf:"varint,5,opt,name=payloadSize" json:"payloadSize,omitempty"`
	// records per segment
	SegmentSize uint32 `protobuf:"varint,6,opt,name=segmentSize" json:"segmentSize,omitempty"`
	// maximum read-only epochs
	MaxROEpochs uint32 `protobuf:"varint,7,opt,name=maxROEpochs" json:"maxROEpochs,omitempty"`
	// maximum read-write epochs
	MaxRWEpochs uint32 `protobuf:"varint,8,opt,name=maxRWEpochs" json:"maxRWEpochs,omitempty"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
