// Code generated by protoc-gen-go.
// source: protocol.proto
// DO NOT EDIT!

/*
Package kdb is a generated protocol buffer package.

It is generated from these files:
	protocol.proto

It has these top-level messages:
	Metadata
*/
package kdb

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Metadata struct {
	BasePath      string `protobuf:"bytes,1,opt,name=basePath" json:"basePath,omitempty"`
	Resolution    int64  `protobuf:"varint,2,opt,name=resolution" json:"resolution,omitempty"`
	EpochDuration int64  `protobuf:"varint,3,opt,name=epochDuration" json:"epochDuration,omitempty"`
	PayloadSize   int64  `protobuf:"varint,4,opt,name=payloadSize" json:"payloadSize,omitempty"`
	SegmentLength int64  `protobuf:"varint,5,opt" json:"SegmentLength,omitempty"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
